server:
  port: 8080

spring:
  profiles:
    active: prod
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 100

logging:
  level:
    root: info
    org.springframework.transaction.interceptor: trace

jwt:
  secret: b8fa78bd08382b806cca62e7fb9e6331a850009acdb69c564a6c0a5f82b053bc0f03976b7cd908d89dfecd840471692633c65736b5d7bfce93f8eb8a5f98e590
  access-token-validation-time: 3600000
  refresh-token-validation-time: 8640000000

---
spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    defer-datasource-initialization: true
---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_mall_fashion
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootuser