name: Automized Deployment to QA server

on:
  push:
    branches: [ release-* ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: wedowhatwedo/mall-qa:latest

#      - name: Deploy to EC2
#        env:
#          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#          HOST: ${{ secrets.EC2_HOST }}
#          USER: ${{ secrets.EC2_USER }}
#        run: |
#          echo "$PRIVATE_KEY" > private_key.pem
#          chmod 600 private_key.pem
#          ssh -i private_key.pem $USER@$HOST << 'EOF'
#            sudo docker pull wedowhatwedo/mall-qa:latest
#            sudo docker stop backend || true
#            sudo docker rm backend || true
#            sudo docker run --rm -d --name backend -p 8080:8080 wedowhatwedo/final3:latest
#          EOF