name: Automized Deployment to QA server

on:
  push:
    branches: [ release-* ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: wedowhatwedo/mall-qa:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo docker pull wedowhatwedo/mall-qa:latest
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker run --rm -d --name backend -p 8080:8080 \
              -e COOLSMS_API_KEY=${{ secrets.COOLSMS_KEY }} \
              -e COOLSMS_API_SECRET=${{ secrets.COOLSMS_SECRET }} \
              -e COOLSMS_API_NUMBER=${{ secrets.COOLSMS_NUMBER }} \
              -e SPRING_MAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} \
              wedowhatwedo/mall-qa:latest